version: "3"
services:
  tidb-0:
    image: pingcap/tidb:v6.1.0
    ports:
      - 4001:4000
    command: /tidb-server -store unistore -path "" -lease 0s > tidb.log 2>&1 &
  tidb-1:
    image: pingcap/tidb:v6.1.0
    ports:
      - 4002:4000
    command: /tidb-server -store unistore -path "" -lease 0s > tidb.log 2>&1 &
  tidb-2:
    image: pingcap/tidb:v6.1.0
    ports:
      - 4003:4000
    command: /tidb-server -store unistore -path "" -lease 0s > tidb.log 2>&1 &
  proxysql:
    image: proxysql/proxysql:latest
    volumes:
    - "./proxysql-user-split.cnf:/etc/proxysql.cnf"
    - "./proxysql-prepare.sql:/proxysql-prepare.sql"
    depends_on:
      - tidb-0
      - tidb-1
      - tidb-2
    links:
      - tidb-0
      - tidb-1
      - tidb-2
    ports:
    - "6034:6033"